### PR TITLE
Firefox OS enhancements

### PR DESCRIPTION
**Pull request by SunboX**
Works now on FFOS, see:

http://youtu.be/2Bhy2wvwDoU

But the scrollMask doesn't fade nicely and I have no clue why this happens. You can reproduce it using regular Firefox Browser.

### CODE REVIEW

**Comment by c2prods** [comment]
I gave it a quick look but apparently the problem comes from .scrollMask's z-index.
I did other changes concerning animation so I had to merge files manually.
I'm reuploading it in a few minutes.
Could you re-test on FFOS?

**Comment by SunboX** [comment]
Ah, ok nice. :) Yep, I will test it again.

**Comment by c2prods** [comment]
Thanks!
I found a bug in the z-index layout, I'm committing once again and it should work on FFOS.
Hence i'm closing this pull request.

**Comment by jeena** [comment]
@c2prods there is something with the buttons, it seems the FxOS browser renders them with some default values. You can check everything yourself in the FxOS simulator (I just tested and it behaves like on the phone, just faster): https://addons.mozilla.org/en-US/firefox/addon/firefox-os-simulator/

**Comment by SunboX** [comment]
Jep, there are some layout bugs ... lets see if I can fix them:

button default background

animation issue 1

animation issue 2

**Comment by c2prods** [comment]
Yep, I've merged latest modifications, should be good now :)

**Pull request closed without merging**
